### PR TITLE
Adding jet studies, unsupervised learning and new workflows and utilities.

### PR DESCRIPTION
**Pull request by janTOffermann**
Adding some new notebooks I've created for modified workflows (and the addition of jet clustering, for studying how we can use our classification + energy regression to improve jet energy resolution). There are a few rough edges due to modifying file management a bit, but it should basically all be in working order.

There are also some new python files, ranging from convenience functions (like progress bars) to custom neural network layers. I think that the latter will be helpful as we explore different network architectures, so that we don't have to define them within notebooks (which can lead to some rather unwieldy code).

I've explicitly included some example models (at least the small ones -- I exclude ResNet as it is >200MB) in the repo.

Lastly, there is a new directory called `setup/`, which contains scripts for setting up the computing environment. This includes creating a `conda` environment for running the workflows, as well as installing `fastjet` for jet clustering. Note that the `fastjet` installation script has some rough edges, it may crash when it attempts to install `fj-core` but this is unnecessary for the time being (and `fastjet` installation itself should work). The basic setup script (`setup/setup.sh`) will also try to install `latex` if it cannot find it, but it does so at a default location that you may want to change. The longer-term plan is to move away from requiring `latex` altogether, so I will likely remove it in a future commit.

The `data/` directory contains some scripts for downloading data -- these are custom scripts that I still have to edit, so that they will work for other users. They access files that may be available to anyone on `lxplus`, but are currently hardcoded to try to login via my account.

### CODE REVIEW

**Comment by mswiatlo** [comment]
Thanks @janTOffermann ! 

Is there any chance you could remove the plots and saved models you have floating around? Those add a lot of 'personal' files to the repo... 

Thanks! I'll merge after you address that.

**Comment by mswiatlo** [comment]
Looks good, thanks!

**Comment by janTOffermann** [comment]
Hi @mswiatlo! All the plots & models should now be removed for the PR. I might later add them back on my fork since it makes it easy to migrate between clusters -- though it would probably be better for me to just host the "default" trained models somewhere else entirely, and include a script that can download them.

**Comment by mswiatlo** [comment]
Yes, sounds good. You can also store those in a separate git area that lives in parallel to this one?

**Pull request merged**
